apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore
  template:
    metadata:
      labels:
        app: bookstore
    spec:
      containers:
      - name: boookstoreapp
        image: us-central1-docker.pkg.dev/cloudregops/bookstore-repo/boookstoreapp:v1
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: bookstore-service
spec:
  type: LoadBalancer
  selector:
    app: bookstore
  ports:
  - port: 80
    targetPort: 3000


