name: CI/CD to GKE

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v3
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v3
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker
      run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet

    - name: Build and push image
      run: |
        IMAGE="${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REPO }}/bookstore-gke:${{ github.sha }}"
        docker build -t $IMAGE .
        docker push $IMAGE
    
    - name: Install gcloud SDK
      uses: google-github-actions/setup-gcloud@v3
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        version: 'latest'
    
    - name: Install gke-gcloud-auth-plugin
      run: |
        gcloud --quiet components install gke-gcloud-auth-plugin
        gke-gcloud-auth-plugin --version || true    
  
    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials bookstore-gke --region ${{ secrets.GCP_REGION }} --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to GKE
      run: |
        IMAGE="${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REPO }}/bookstore-gke:${{ github.sha }}"
        kubectl set image deployment/bookstore-deployment bookstore=$IMAGE --record
        kubectl rollout status deployment/bookstore-deployment --timeout=120s
